audio:
  _target_: mmdisco.models.networks.AudioInferenceConfig
  length_in_sec: 2
  ch_guidance: False

video:
  _target_: mmdisco.models.networks.VideoInferenceConfig
  height: 256
  width: 256
  num_frames: 16
  ch_guidance: False

num_samples_per_prompt: 4
prompts:
  [
    "playing hammond organ",
    "playing bongo",
    "playing saxophone",
    "fireworks banging",
    "female speech, woman speaking",
    "Man speaking",
    "crow cawing",
    "chainsawing trees",
    "fire crackling",
    "ocean waves",
    "airplane flyby",
    "orchestra",
  ]

num_inference_steps: 50
joint: True
joint_scale_audio: 1.0
joint_scale_video: 8.0
joint_num_steps: 1
